---
- name: Add DNS record
  google.cloud.gcp_dns_resource_record_set:
    name: "{{ appname }}.ycdisp.net."
    managed_zone: "{{ managed_zone }}"
    type: "{{ record_type }}"
    ttl: 300
    target:
      - "{{ target }}"
    project: proj-yc-srv1
    auth_kind: serviceaccount
    service_account_file: "{{ lookup('template', 'gcp-creds.json.j2') }}"
    state: present
