---
- name: Create gcp sa json file on host
  ansible.builtin.template:
    src: gcp-creds.json.j2
    dest: gcp-creds.json
    mode: '0600'

- name: Get managed zone info
  google.cloud.gcp_dns_managed_zone_info:
    dns_name: ycdisp.net.
    project: proj-yc-srv1
    auth_kind: serviceaccount
    service_account_file: "gcp-creds.json"
  register: managed_zone

# - ansible.builtin.debug:
#     var: managed_zone['resources']

- name: Add DNS record
  google.cloud.gcp_dns_resource_record_set:
    name: "{{ hostname }}.ycdisp.net."
    managed_zone: "{{ managed_zone['resources'] }}"
    type: "{{ record_type }}"
    ttl: 300
    target:
      - "{{ target }}"
    project: proj-yc-srv1
    auth_kind: serviceaccount
    service_account_file: "gcp-creds.json"
    state: present

- name: Remove gcp sa json file
  ansible.builtin.file:
    path: gcp-creds.json
    state: absent
