---
- name: Create gcp sa json file on host
  ansible.builtin.template:
    src: gcp-creds.json.j2
    dest: /tmp/gcp-creds.json
    mode: '0644'

- name: Remove DNS record
  google.cloud.gcp_dns_resource_record_set:
    name: "{{ hostname }}.ycdisp.net."
    managed_zone: "{{ managed_zone }}"
    type: "{{ record_type }}"
    ttl: 300
    target:
      - "{{ target }}"
    project: proj-yc-srv1
    auth_kind: serviceaccount
    service_account_file: "/tmp/gcp-creds.json"
    state: absent

- name: Remove gcp sa json file
  ansible.builtin.file:
    path: /tmp/gcp-creds.json
    state: absent